/*
 * Merge Accounting API
 *
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * API version: 1.0
 * Contact: hello@merge.dev
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merge_accounting_client

import (
	"encoding/json"
)

// PaginatedPurchaseOrderList struct for PaginatedPurchaseOrderList
type PaginatedPurchaseOrderList struct {
	Next NullableString `json:"next,omitempty"`
	Previous NullableString `json:"previous,omitempty"`
	Results *[]PurchaseOrder `json:"results,omitempty"`
	// raw json response by property name
	ResponseRaw map[string]json.RawMessage `json:"-"`
}

// NewPaginatedPurchaseOrderList instantiates a new PaginatedPurchaseOrderList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedPurchaseOrderList() *PaginatedPurchaseOrderList {
	this := PaginatedPurchaseOrderList{}
	return &this
}

// NewPaginatedPurchaseOrderListWithDefaults instantiates a new PaginatedPurchaseOrderList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedPurchaseOrderListWithDefaults() *PaginatedPurchaseOrderList {
	this := PaginatedPurchaseOrderList{}
	return &this
}

// GetNext returns the Next field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedPurchaseOrderList) GetNext() string {
	if o == nil || o.Next.Get() == nil {
		var ret string
		return ret
	}
	return *o.Next.Get()
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedPurchaseOrderList) GetNextOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Next.Get(), o.Next.IsSet()
}

// HasNext returns a boolean if a field has been set.
func (o *PaginatedPurchaseOrderList) HasNext() bool {
	if o != nil && o.Next.IsSet() {
		return true
	}

	return false
}

// SetNext gets a reference to the given NullableString and assigns it to the Next field.
func (o *PaginatedPurchaseOrderList) SetNext(v string) {
	o.Next.Set(&v)
}
// SetNextNil sets the value for Next to be an explicit nil
func (o *PaginatedPurchaseOrderList) SetNextNil() {
	o.Next.Set(nil)
}

// UnsetNext ensures that no value is present for Next, not even an explicit nil
func (o *PaginatedPurchaseOrderList) UnsetNext() {
	o.Next.Unset()
}

// GetPrevious returns the Previous field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedPurchaseOrderList) GetPrevious() string {
	if o == nil || o.Previous.Get() == nil {
		var ret string
		return ret
	}
	return *o.Previous.Get()
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedPurchaseOrderList) GetPreviousOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Previous.Get(), o.Previous.IsSet()
}

// HasPrevious returns a boolean if a field has been set.
func (o *PaginatedPurchaseOrderList) HasPrevious() bool {
	if o != nil && o.Previous.IsSet() {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given NullableString and assigns it to the Previous field.
func (o *PaginatedPurchaseOrderList) SetPrevious(v string) {
	o.Previous.Set(&v)
}
// SetPreviousNil sets the value for Previous to be an explicit nil
func (o *PaginatedPurchaseOrderList) SetPreviousNil() {
	o.Previous.Set(nil)
}

// UnsetPrevious ensures that no value is present for Previous, not even an explicit nil
func (o *PaginatedPurchaseOrderList) UnsetPrevious() {
	o.Previous.Unset()
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *PaginatedPurchaseOrderList) GetResults() []PurchaseOrder {
	if o == nil || o.Results == nil {
		var ret []PurchaseOrder
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedPurchaseOrderList) GetResultsOk() (*[]PurchaseOrder, bool) {
	if o == nil || o.Results == nil {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *PaginatedPurchaseOrderList) HasResults() bool {
	if o != nil && o.Results != nil {
		return true
	}

	return false
}

// SetResults gets a reference to the given []PurchaseOrder and assigns it to the Results field.
func (o *PaginatedPurchaseOrderList) SetResults(v []PurchaseOrder) {
	o.Results = &v
}

func (o PaginatedPurchaseOrderList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Next.IsSet() {
		toSerialize["next"] = o.Next.Get()
	}
	if o.Previous.IsSet() {
		toSerialize["previous"] = o.Previous.Get()
	}
	if o.Results != nil {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

func (v *PaginatedPurchaseOrderList) UnmarshalJSON(src []byte) error {
    type PaginatedPurchaseOrderListUnmarshalTarget PaginatedPurchaseOrderList

	var intermediateResult PaginatedPurchaseOrderListUnmarshalTarget
	var err1 = json.Unmarshal(src, &intermediateResult)
    if err1 != nil {
        return err1
    }
    var err2 = json.Unmarshal(src, &intermediateResult.ResponseRaw)
	if err2 != nil {
		return err2
	}

	*v = PaginatedPurchaseOrderList(intermediateResult)
	return nil
}
type NullablePaginatedPurchaseOrderList struct {
	value *PaginatedPurchaseOrderList
	isSet bool
}

func (v NullablePaginatedPurchaseOrderList) Get() *PaginatedPurchaseOrderList {
	return v.value
}

func (v *NullablePaginatedPurchaseOrderList) Set(val *PaginatedPurchaseOrderList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedPurchaseOrderList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedPurchaseOrderList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedPurchaseOrderList(val *PaginatedPurchaseOrderList) *NullablePaginatedPurchaseOrderList {
	return &NullablePaginatedPurchaseOrderList{value: val, isSet: true}
}

func (v NullablePaginatedPurchaseOrderList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedPurchaseOrderList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	var err1 = json.Unmarshal(src, &v.value)
    if err1 != nil {
        return err1
    }
    return json.Unmarshal(src, &v.value.ResponseRaw)
}


