/*
 * Merge Accounting API
 *
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * API version: 1.0
 * Contact: hello@merge.dev
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merge_accounting_client

import (
	"encoding/json"
)

// PaymentEndpointRequest struct for PaymentEndpointRequest
type PaymentEndpointRequest struct {
	Model PaymentRequest `json:"model"`
	// raw json response by property name
	ResponseRaw map[string]json.RawMessage `json:"-"`
}

// NewPaymentEndpointRequest instantiates a new PaymentEndpointRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentEndpointRequest(model PaymentRequest) *PaymentEndpointRequest {
	this := PaymentEndpointRequest{}
	this.Model = model
	return &this
}

// NewPaymentEndpointRequestWithDefaults instantiates a new PaymentEndpointRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentEndpointRequestWithDefaults() *PaymentEndpointRequest {
	this := PaymentEndpointRequest{}
	return &this
}

// GetModel returns the Model field value
func (o *PaymentEndpointRequest) GetModel() PaymentRequest {
	if o == nil {
		var ret PaymentRequest
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *PaymentEndpointRequest) GetModelOk() (*PaymentRequest, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *PaymentEndpointRequest) SetModel(v PaymentRequest) {
	o.Model = v
}

func (o PaymentEndpointRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["model"] = o.Model
	}
	return json.Marshal(toSerialize)
}

func (v *PaymentEndpointRequest) UnmarshalJSON(src []byte) error {
    type PaymentEndpointRequestUnmarshalTarget PaymentEndpointRequest

	var intermediateResult PaymentEndpointRequestUnmarshalTarget
	var err1 = json.Unmarshal(src, &intermediateResult)
    if err1 != nil {
        return err1
    }
    var err2 = json.Unmarshal(src, &intermediateResult.ResponseRaw)
	if err2 != nil {
		return err2
	}

	*v = PaymentEndpointRequest(intermediateResult)
	return nil
}
type NullablePaymentEndpointRequest struct {
	value *PaymentEndpointRequest
	isSet bool
}

func (v NullablePaymentEndpointRequest) Get() *PaymentEndpointRequest {
	return v.value
}

func (v *NullablePaymentEndpointRequest) Set(val *PaymentEndpointRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentEndpointRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentEndpointRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentEndpointRequest(val *PaymentEndpointRequest) *NullablePaymentEndpointRequest {
	return &NullablePaymentEndpointRequest{value: val, isSet: true}
}

func (v NullablePaymentEndpointRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentEndpointRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	var err1 = json.Unmarshal(src, &v.value)
    if err1 != nil {
        return err1
    }
    return json.Unmarshal(src, &v.value.ResponseRaw)
}


