/*
 * Merge Accounting API
 *
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * API version: 1.0
 * Contact: hello@merge.dev
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merge_accounting_client

import (
	"encoding/json"
	"fmt"
)

// CurrencyEnum the model 'CurrencyEnum'
type CurrencyEnum string

// apologies but this is to get around an import error
var _ = fmt.Printf
// List of CurrencyEnum
const (
    CURRENCYENUM_MERGE_NONSTANDARD_VALUE CurrencyEnum = "MERGE_NONSTANDARD_VALUE"
    
	CURRENCYENUM_XUA CurrencyEnum = "XUA"
	CURRENCYENUM_AFN CurrencyEnum = "AFN"
	CURRENCYENUM_AFA CurrencyEnum = "AFA"
	CURRENCYENUM_ALL CurrencyEnum = "ALL"
	CURRENCYENUM_ALK CurrencyEnum = "ALK"
	CURRENCYENUM_DZD CurrencyEnum = "DZD"
	CURRENCYENUM_ADP CurrencyEnum = "ADP"
	CURRENCYENUM_AOA CurrencyEnum = "AOA"
	CURRENCYENUM_AOK CurrencyEnum = "AOK"
	CURRENCYENUM_AON CurrencyEnum = "AON"
	CURRENCYENUM_AOR CurrencyEnum = "AOR"
	CURRENCYENUM_ARA CurrencyEnum = "ARA"
	CURRENCYENUM_ARS CurrencyEnum = "ARS"
	CURRENCYENUM_ARM CurrencyEnum = "ARM"
	CURRENCYENUM_ARP CurrencyEnum = "ARP"
	CURRENCYENUM_ARL CurrencyEnum = "ARL"
	CURRENCYENUM_AMD CurrencyEnum = "AMD"
	CURRENCYENUM_AWG CurrencyEnum = "AWG"
	CURRENCYENUM_AUD CurrencyEnum = "AUD"
	CURRENCYENUM_ATS CurrencyEnum = "ATS"
	CURRENCYENUM_AZN CurrencyEnum = "AZN"
	CURRENCYENUM_AZM CurrencyEnum = "AZM"
	CURRENCYENUM_BSD CurrencyEnum = "BSD"
	CURRENCYENUM_BHD CurrencyEnum = "BHD"
	CURRENCYENUM_BDT CurrencyEnum = "BDT"
	CURRENCYENUM_BBD CurrencyEnum = "BBD"
	CURRENCYENUM_BYN CurrencyEnum = "BYN"
	CURRENCYENUM_BYB CurrencyEnum = "BYB"
	CURRENCYENUM_BYR CurrencyEnum = "BYR"
	CURRENCYENUM_BEF CurrencyEnum = "BEF"
	CURRENCYENUM_BEC CurrencyEnum = "BEC"
	CURRENCYENUM_BEL CurrencyEnum = "BEL"
	CURRENCYENUM_BZD CurrencyEnum = "BZD"
	CURRENCYENUM_BMD CurrencyEnum = "BMD"
	CURRENCYENUM_BTN CurrencyEnum = "BTN"
	CURRENCYENUM_BOB CurrencyEnum = "BOB"
	CURRENCYENUM_BOL CurrencyEnum = "BOL"
	CURRENCYENUM_BOV CurrencyEnum = "BOV"
	CURRENCYENUM_BOP CurrencyEnum = "BOP"
	CURRENCYENUM_BAM CurrencyEnum = "BAM"
	CURRENCYENUM_BAD CurrencyEnum = "BAD"
	CURRENCYENUM_BAN CurrencyEnum = "BAN"
	CURRENCYENUM_BWP CurrencyEnum = "BWP"
	CURRENCYENUM_BRC CurrencyEnum = "BRC"
	CURRENCYENUM_BRZ CurrencyEnum = "BRZ"
	CURRENCYENUM_BRE CurrencyEnum = "BRE"
	CURRENCYENUM_BRR CurrencyEnum = "BRR"
	CURRENCYENUM_BRN CurrencyEnum = "BRN"
	CURRENCYENUM_BRB CurrencyEnum = "BRB"
	CURRENCYENUM_BRL CurrencyEnum = "BRL"
	CURRENCYENUM_GBP CurrencyEnum = "GBP"
	CURRENCYENUM_BND CurrencyEnum = "BND"
	CURRENCYENUM_BGL CurrencyEnum = "BGL"
	CURRENCYENUM_BGN CurrencyEnum = "BGN"
	CURRENCYENUM_BGO CurrencyEnum = "BGO"
	CURRENCYENUM_BGM CurrencyEnum = "BGM"
	CURRENCYENUM_BUK CurrencyEnum = "BUK"
	CURRENCYENUM_BIF CurrencyEnum = "BIF"
	CURRENCYENUM_XPF CurrencyEnum = "XPF"
	CURRENCYENUM_KHR CurrencyEnum = "KHR"
	CURRENCYENUM_CAD CurrencyEnum = "CAD"
	CURRENCYENUM_CVE CurrencyEnum = "CVE"
	CURRENCYENUM_KYD CurrencyEnum = "KYD"
	CURRENCYENUM_XAF CurrencyEnum = "XAF"
	CURRENCYENUM_CLE CurrencyEnum = "CLE"
	CURRENCYENUM_CLP CurrencyEnum = "CLP"
	CURRENCYENUM_CLF CurrencyEnum = "CLF"
	CURRENCYENUM_CNX CurrencyEnum = "CNX"
	CURRENCYENUM_CNY CurrencyEnum = "CNY"
	CURRENCYENUM_CNH CurrencyEnum = "CNH"
	CURRENCYENUM_COP CurrencyEnum = "COP"
	CURRENCYENUM_COU CurrencyEnum = "COU"
	CURRENCYENUM_KMF CurrencyEnum = "KMF"
	CURRENCYENUM_CDF CurrencyEnum = "CDF"
	CURRENCYENUM_CRC CurrencyEnum = "CRC"
	CURRENCYENUM_HRD CurrencyEnum = "HRD"
	CURRENCYENUM_HRK CurrencyEnum = "HRK"
	CURRENCYENUM_CUC CurrencyEnum = "CUC"
	CURRENCYENUM_CUP CurrencyEnum = "CUP"
	CURRENCYENUM_CYP CurrencyEnum = "CYP"
	CURRENCYENUM_CZK CurrencyEnum = "CZK"
	CURRENCYENUM_CSK CurrencyEnum = "CSK"
	CURRENCYENUM_DKK CurrencyEnum = "DKK"
	CURRENCYENUM_DJF CurrencyEnum = "DJF"
	CURRENCYENUM_DOP CurrencyEnum = "DOP"
	CURRENCYENUM_NLG CurrencyEnum = "NLG"
	CURRENCYENUM_XCD CurrencyEnum = "XCD"
	CURRENCYENUM_DDM CurrencyEnum = "DDM"
	CURRENCYENUM_ECS CurrencyEnum = "ECS"
	CURRENCYENUM_ECV CurrencyEnum = "ECV"
	CURRENCYENUM_EGP CurrencyEnum = "EGP"
	CURRENCYENUM_GQE CurrencyEnum = "GQE"
	CURRENCYENUM_ERN CurrencyEnum = "ERN"
	CURRENCYENUM_EEK CurrencyEnum = "EEK"
	CURRENCYENUM_ETB CurrencyEnum = "ETB"
	CURRENCYENUM_EUR CurrencyEnum = "EUR"
	CURRENCYENUM_XBA CurrencyEnum = "XBA"
	CURRENCYENUM_XEU CurrencyEnum = "XEU"
	CURRENCYENUM_XBB CurrencyEnum = "XBB"
	CURRENCYENUM_XBC CurrencyEnum = "XBC"
	CURRENCYENUM_XBD CurrencyEnum = "XBD"
	CURRENCYENUM_FKP CurrencyEnum = "FKP"
	CURRENCYENUM_FJD CurrencyEnum = "FJD"
	CURRENCYENUM_FIM CurrencyEnum = "FIM"
	CURRENCYENUM_FRF CurrencyEnum = "FRF"
	CURRENCYENUM_XFO CurrencyEnum = "XFO"
	CURRENCYENUM_XFU CurrencyEnum = "XFU"
	CURRENCYENUM_GMD CurrencyEnum = "GMD"
	CURRENCYENUM_GEK CurrencyEnum = "GEK"
	CURRENCYENUM_GEL CurrencyEnum = "GEL"
	CURRENCYENUM_DEM CurrencyEnum = "DEM"
	CURRENCYENUM_GHS CurrencyEnum = "GHS"
	CURRENCYENUM_GHC CurrencyEnum = "GHC"
	CURRENCYENUM_GIP CurrencyEnum = "GIP"
	CURRENCYENUM_XAU CurrencyEnum = "XAU"
	CURRENCYENUM_GRD CurrencyEnum = "GRD"
	CURRENCYENUM_GTQ CurrencyEnum = "GTQ"
	CURRENCYENUM_GWP CurrencyEnum = "GWP"
	CURRENCYENUM_GNF CurrencyEnum = "GNF"
	CURRENCYENUM_GNS CurrencyEnum = "GNS"
	CURRENCYENUM_GYD CurrencyEnum = "GYD"
	CURRENCYENUM_HTG CurrencyEnum = "HTG"
	CURRENCYENUM_HNL CurrencyEnum = "HNL"
	CURRENCYENUM_HKD CurrencyEnum = "HKD"
	CURRENCYENUM_HUF CurrencyEnum = "HUF"
	CURRENCYENUM_IMP CurrencyEnum = "IMP"
	CURRENCYENUM_ISK CurrencyEnum = "ISK"
	CURRENCYENUM_ISJ CurrencyEnum = "ISJ"
	CURRENCYENUM_INR CurrencyEnum = "INR"
	CURRENCYENUM_IDR CurrencyEnum = "IDR"
	CURRENCYENUM_IRR CurrencyEnum = "IRR"
	CURRENCYENUM_IQD CurrencyEnum = "IQD"
	CURRENCYENUM_IEP CurrencyEnum = "IEP"
	CURRENCYENUM_ILS CurrencyEnum = "ILS"
	CURRENCYENUM_ILP CurrencyEnum = "ILP"
	CURRENCYENUM_ILR CurrencyEnum = "ILR"
	CURRENCYENUM_ITL CurrencyEnum = "ITL"
	CURRENCYENUM_JMD CurrencyEnum = "JMD"
	CURRENCYENUM_JPY CurrencyEnum = "JPY"
	CURRENCYENUM_JOD CurrencyEnum = "JOD"
	CURRENCYENUM_KZT CurrencyEnum = "KZT"
	CURRENCYENUM_KES CurrencyEnum = "KES"
	CURRENCYENUM_KWD CurrencyEnum = "KWD"
	CURRENCYENUM_KGS CurrencyEnum = "KGS"
	CURRENCYENUM_LAK CurrencyEnum = "LAK"
	CURRENCYENUM_LVL CurrencyEnum = "LVL"
	CURRENCYENUM_LVR CurrencyEnum = "LVR"
	CURRENCYENUM_LBP CurrencyEnum = "LBP"
	CURRENCYENUM_LSL CurrencyEnum = "LSL"
	CURRENCYENUM_LRD CurrencyEnum = "LRD"
	CURRENCYENUM_LYD CurrencyEnum = "LYD"
	CURRENCYENUM_LTL CurrencyEnum = "LTL"
	CURRENCYENUM_LTT CurrencyEnum = "LTT"
	CURRENCYENUM_LUL CurrencyEnum = "LUL"
	CURRENCYENUM_LUC CurrencyEnum = "LUC"
	CURRENCYENUM_LUF CurrencyEnum = "LUF"
	CURRENCYENUM_MOP CurrencyEnum = "MOP"
	CURRENCYENUM_MKD CurrencyEnum = "MKD"
	CURRENCYENUM_MKN CurrencyEnum = "MKN"
	CURRENCYENUM_MGA CurrencyEnum = "MGA"
	CURRENCYENUM_MGF CurrencyEnum = "MGF"
	CURRENCYENUM_MWK CurrencyEnum = "MWK"
	CURRENCYENUM_MYR CurrencyEnum = "MYR"
	CURRENCYENUM_MVR CurrencyEnum = "MVR"
	CURRENCYENUM_MVP CurrencyEnum = "MVP"
	CURRENCYENUM_MLF CurrencyEnum = "MLF"
	CURRENCYENUM_MTL CurrencyEnum = "MTL"
	CURRENCYENUM_MTP CurrencyEnum = "MTP"
	CURRENCYENUM_MRU CurrencyEnum = "MRU"
	CURRENCYENUM_MRO CurrencyEnum = "MRO"
	CURRENCYENUM_MUR CurrencyEnum = "MUR"
	CURRENCYENUM_MXV CurrencyEnum = "MXV"
	CURRENCYENUM_MXN CurrencyEnum = "MXN"
	CURRENCYENUM_MXP CurrencyEnum = "MXP"
	CURRENCYENUM_MDC CurrencyEnum = "MDC"
	CURRENCYENUM_MDL CurrencyEnum = "MDL"
	CURRENCYENUM_MCF CurrencyEnum = "MCF"
	CURRENCYENUM_MNT CurrencyEnum = "MNT"
	CURRENCYENUM_MAD CurrencyEnum = "MAD"
	CURRENCYENUM_MAF CurrencyEnum = "MAF"
	CURRENCYENUM_MZE CurrencyEnum = "MZE"
	CURRENCYENUM_MZN CurrencyEnum = "MZN"
	CURRENCYENUM_MZM CurrencyEnum = "MZM"
	CURRENCYENUM_MMK CurrencyEnum = "MMK"
	CURRENCYENUM_NAD CurrencyEnum = "NAD"
	CURRENCYENUM_NPR CurrencyEnum = "NPR"
	CURRENCYENUM_ANG CurrencyEnum = "ANG"
	CURRENCYENUM_TWD CurrencyEnum = "TWD"
	CURRENCYENUM_NZD CurrencyEnum = "NZD"
	CURRENCYENUM_NIO CurrencyEnum = "NIO"
	CURRENCYENUM_NIC CurrencyEnum = "NIC"
	CURRENCYENUM_NGN CurrencyEnum = "NGN"
	CURRENCYENUM_KPW CurrencyEnum = "KPW"
	CURRENCYENUM_NOK CurrencyEnum = "NOK"
	CURRENCYENUM_OMR CurrencyEnum = "OMR"
	CURRENCYENUM_PKR CurrencyEnum = "PKR"
	CURRENCYENUM_XPD CurrencyEnum = "XPD"
	CURRENCYENUM_PAB CurrencyEnum = "PAB"
	CURRENCYENUM_PGK CurrencyEnum = "PGK"
	CURRENCYENUM_PYG CurrencyEnum = "PYG"
	CURRENCYENUM_PEI CurrencyEnum = "PEI"
	CURRENCYENUM_PEN CurrencyEnum = "PEN"
	CURRENCYENUM_PES CurrencyEnum = "PES"
	CURRENCYENUM_PHP CurrencyEnum = "PHP"
	CURRENCYENUM_XPT CurrencyEnum = "XPT"
	CURRENCYENUM_PLN CurrencyEnum = "PLN"
	CURRENCYENUM_PLZ CurrencyEnum = "PLZ"
	CURRENCYENUM_PTE CurrencyEnum = "PTE"
	CURRENCYENUM_GWE CurrencyEnum = "GWE"
	CURRENCYENUM_QAR CurrencyEnum = "QAR"
	CURRENCYENUM_XRE CurrencyEnum = "XRE"
	CURRENCYENUM_RHD CurrencyEnum = "RHD"
	CURRENCYENUM_RON CurrencyEnum = "RON"
	CURRENCYENUM_ROL CurrencyEnum = "ROL"
	CURRENCYENUM_RUB CurrencyEnum = "RUB"
	CURRENCYENUM_RUR CurrencyEnum = "RUR"
	CURRENCYENUM_RWF CurrencyEnum = "RWF"
	CURRENCYENUM_SVC CurrencyEnum = "SVC"
	CURRENCYENUM_WST CurrencyEnum = "WST"
	CURRENCYENUM_SAR CurrencyEnum = "SAR"
	CURRENCYENUM_RSD CurrencyEnum = "RSD"
	CURRENCYENUM_CSD CurrencyEnum = "CSD"
	CURRENCYENUM_SCR CurrencyEnum = "SCR"
	CURRENCYENUM_SLL CurrencyEnum = "SLL"
	CURRENCYENUM_XAG CurrencyEnum = "XAG"
	CURRENCYENUM_SGD CurrencyEnum = "SGD"
	CURRENCYENUM_SKK CurrencyEnum = "SKK"
	CURRENCYENUM_SIT CurrencyEnum = "SIT"
	CURRENCYENUM_SBD CurrencyEnum = "SBD"
	CURRENCYENUM_SOS CurrencyEnum = "SOS"
	CURRENCYENUM_ZAR CurrencyEnum = "ZAR"
	CURRENCYENUM_ZAL CurrencyEnum = "ZAL"
	CURRENCYENUM_KRH CurrencyEnum = "KRH"
	CURRENCYENUM_KRW CurrencyEnum = "KRW"
	CURRENCYENUM_KRO CurrencyEnum = "KRO"
	CURRENCYENUM_SSP CurrencyEnum = "SSP"
	CURRENCYENUM_SUR CurrencyEnum = "SUR"
	CURRENCYENUM_ESP CurrencyEnum = "ESP"
	CURRENCYENUM_ESA CurrencyEnum = "ESA"
	CURRENCYENUM_ESB CurrencyEnum = "ESB"
	CURRENCYENUM_XDR CurrencyEnum = "XDR"
	CURRENCYENUM_LKR CurrencyEnum = "LKR"
	CURRENCYENUM_SHP CurrencyEnum = "SHP"
	CURRENCYENUM_XSU CurrencyEnum = "XSU"
	CURRENCYENUM_SDD CurrencyEnum = "SDD"
	CURRENCYENUM_SDG CurrencyEnum = "SDG"
	CURRENCYENUM_SDP CurrencyEnum = "SDP"
	CURRENCYENUM_SRD CurrencyEnum = "SRD"
	CURRENCYENUM_SRG CurrencyEnum = "SRG"
	CURRENCYENUM_SZL CurrencyEnum = "SZL"
	CURRENCYENUM_SEK CurrencyEnum = "SEK"
	CURRENCYENUM_CHF CurrencyEnum = "CHF"
	CURRENCYENUM_SYP CurrencyEnum = "SYP"
	CURRENCYENUM_STN CurrencyEnum = "STN"
	CURRENCYENUM_STD CurrencyEnum = "STD"
	CURRENCYENUM_TVD CurrencyEnum = "TVD"
	CURRENCYENUM_TJR CurrencyEnum = "TJR"
	CURRENCYENUM_TJS CurrencyEnum = "TJS"
	CURRENCYENUM_TZS CurrencyEnum = "TZS"
	CURRENCYENUM_XTS CurrencyEnum = "XTS"
	CURRENCYENUM_THB CurrencyEnum = "THB"
	CURRENCYENUM_XXX CurrencyEnum = "XXX"
	CURRENCYENUM_TPE CurrencyEnum = "TPE"
	CURRENCYENUM_TOP CurrencyEnum = "TOP"
	CURRENCYENUM_TTD CurrencyEnum = "TTD"
	CURRENCYENUM_TND CurrencyEnum = "TND"
	CURRENCYENUM_TRY CurrencyEnum = "TRY"
	CURRENCYENUM_TRL CurrencyEnum = "TRL"
	CURRENCYENUM_TMT CurrencyEnum = "TMT"
	CURRENCYENUM_TMM CurrencyEnum = "TMM"
	CURRENCYENUM_USD CurrencyEnum = "USD"
	CURRENCYENUM_USN CurrencyEnum = "USN"
	CURRENCYENUM_USS CurrencyEnum = "USS"
	CURRENCYENUM_UGX CurrencyEnum = "UGX"
	CURRENCYENUM_UGS CurrencyEnum = "UGS"
	CURRENCYENUM_UAH CurrencyEnum = "UAH"
	CURRENCYENUM_UAK CurrencyEnum = "UAK"
	CURRENCYENUM_AED CurrencyEnum = "AED"
	CURRENCYENUM_UYW CurrencyEnum = "UYW"
	CURRENCYENUM_UYU CurrencyEnum = "UYU"
	CURRENCYENUM_UYP CurrencyEnum = "UYP"
	CURRENCYENUM_UYI CurrencyEnum = "UYI"
	CURRENCYENUM_UZS CurrencyEnum = "UZS"
	CURRENCYENUM_VUV CurrencyEnum = "VUV"
	CURRENCYENUM_VES CurrencyEnum = "VES"
	CURRENCYENUM_VEB CurrencyEnum = "VEB"
	CURRENCYENUM_VEF CurrencyEnum = "VEF"
	CURRENCYENUM_VND CurrencyEnum = "VND"
	CURRENCYENUM_VNN CurrencyEnum = "VNN"
	CURRENCYENUM_CHE CurrencyEnum = "CHE"
	CURRENCYENUM_CHW CurrencyEnum = "CHW"
	CURRENCYENUM_XOF CurrencyEnum = "XOF"
	CURRENCYENUM_YDD CurrencyEnum = "YDD"
	CURRENCYENUM_YER CurrencyEnum = "YER"
	CURRENCYENUM_YUN CurrencyEnum = "YUN"
	CURRENCYENUM_YUD CurrencyEnum = "YUD"
	CURRENCYENUM_YUM CurrencyEnum = "YUM"
	CURRENCYENUM_YUR CurrencyEnum = "YUR"
	CURRENCYENUM_ZWN CurrencyEnum = "ZWN"
	CURRENCYENUM_ZRN CurrencyEnum = "ZRN"
	CURRENCYENUM_ZRZ CurrencyEnum = "ZRZ"
	CURRENCYENUM_ZMW CurrencyEnum = "ZMW"
	CURRENCYENUM_ZMK CurrencyEnum = "ZMK"
	CURRENCYENUM_ZWD CurrencyEnum = "ZWD"
	CURRENCYENUM_ZWR CurrencyEnum = "ZWR"
	CURRENCYENUM_ZWL CurrencyEnum = "ZWL"
)

var allowedCurrencyEnumEnumValues = []CurrencyEnum{
	"XUA",
	"AFN",
	"AFA",
	"ALL",
	"ALK",
	"DZD",
	"ADP",
	"AOA",
	"AOK",
	"AON",
	"AOR",
	"ARA",
	"ARS",
	"ARM",
	"ARP",
	"ARL",
	"AMD",
	"AWG",
	"AUD",
	"ATS",
	"AZN",
	"AZM",
	"BSD",
	"BHD",
	"BDT",
	"BBD",
	"BYN",
	"BYB",
	"BYR",
	"BEF",
	"BEC",
	"BEL",
	"BZD",
	"BMD",
	"BTN",
	"BOB",
	"BOL",
	"BOV",
	"BOP",
	"BAM",
	"BAD",
	"BAN",
	"BWP",
	"BRC",
	"BRZ",
	"BRE",
	"BRR",
	"BRN",
	"BRB",
	"BRL",
	"GBP",
	"BND",
	"BGL",
	"BGN",
	"BGO",
	"BGM",
	"BUK",
	"BIF",
	"XPF",
	"KHR",
	"CAD",
	"CVE",
	"KYD",
	"XAF",
	"CLE",
	"CLP",
	"CLF",
	"CNX",
	"CNY",
	"CNH",
	"COP",
	"COU",
	"KMF",
	"CDF",
	"CRC",
	"HRD",
	"HRK",
	"CUC",
	"CUP",
	"CYP",
	"CZK",
	"CSK",
	"DKK",
	"DJF",
	"DOP",
	"NLG",
	"XCD",
	"DDM",
	"ECS",
	"ECV",
	"EGP",
	"GQE",
	"ERN",
	"EEK",
	"ETB",
	"EUR",
	"XBA",
	"XEU",
	"XBB",
	"XBC",
	"XBD",
	"FKP",
	"FJD",
	"FIM",
	"FRF",
	"XFO",
	"XFU",
	"GMD",
	"GEK",
	"GEL",
	"DEM",
	"GHS",
	"GHC",
	"GIP",
	"XAU",
	"GRD",
	"GTQ",
	"GWP",
	"GNF",
	"GNS",
	"GYD",
	"HTG",
	"HNL",
	"HKD",
	"HUF",
	"IMP",
	"ISK",
	"ISJ",
	"INR",
	"IDR",
	"IRR",
	"IQD",
	"IEP",
	"ILS",
	"ILP",
	"ILR",
	"ITL",
	"JMD",
	"JPY",
	"JOD",
	"KZT",
	"KES",
	"KWD",
	"KGS",
	"LAK",
	"LVL",
	"LVR",
	"LBP",
	"LSL",
	"LRD",
	"LYD",
	"LTL",
	"LTT",
	"LUL",
	"LUC",
	"LUF",
	"MOP",
	"MKD",
	"MKN",
	"MGA",
	"MGF",
	"MWK",
	"MYR",
	"MVR",
	"MVP",
	"MLF",
	"MTL",
	"MTP",
	"MRU",
	"MRO",
	"MUR",
	"MXV",
	"MXN",
	"MXP",
	"MDC",
	"MDL",
	"MCF",
	"MNT",
	"MAD",
	"MAF",
	"MZE",
	"MZN",
	"MZM",
	"MMK",
	"NAD",
	"NPR",
	"ANG",
	"TWD",
	"NZD",
	"NIO",
	"NIC",
	"NGN",
	"KPW",
	"NOK",
	"OMR",
	"PKR",
	"XPD",
	"PAB",
	"PGK",
	"PYG",
	"PEI",
	"PEN",
	"PES",
	"PHP",
	"XPT",
	"PLN",
	"PLZ",
	"PTE",
	"GWE",
	"QAR",
	"XRE",
	"RHD",
	"RON",
	"ROL",
	"RUB",
	"RUR",
	"RWF",
	"SVC",
	"WST",
	"SAR",
	"RSD",
	"CSD",
	"SCR",
	"SLL",
	"XAG",
	"SGD",
	"SKK",
	"SIT",
	"SBD",
	"SOS",
	"ZAR",
	"ZAL",
	"KRH",
	"KRW",
	"KRO",
	"SSP",
	"SUR",
	"ESP",
	"ESA",
	"ESB",
	"XDR",
	"LKR",
	"SHP",
	"XSU",
	"SDD",
	"SDG",
	"SDP",
	"SRD",
	"SRG",
	"SZL",
	"SEK",
	"CHF",
	"SYP",
	"STN",
	"STD",
	"TVD",
	"TJR",
	"TJS",
	"TZS",
	"XTS",
	"THB",
	"XXX",
	"TPE",
	"TOP",
	"TTD",
	"TND",
	"TRY",
	"TRL",
	"TMT",
	"TMM",
	"USD",
	"USN",
	"USS",
	"UGX",
	"UGS",
	"UAH",
	"UAK",
	"AED",
	"UYW",
	"UYU",
	"UYP",
	"UYI",
	"UZS",
	"VUV",
	"VES",
	"VEB",
	"VEF",
	"VND",
	"VNN",
	"CHE",
	"CHW",
	"XOF",
	"YDD",
	"YER",
	"YUN",
	"YUD",
	"YUM",
	"YUR",
	"ZWN",
	"ZRN",
	"ZRZ",
	"ZMW",
	"ZMK",
	"ZWD",
	"ZWR",
	"ZWL",
}

func (v *CurrencyEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CurrencyEnum(value)
	for _, existing := range allowedCurrencyEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}
    *v = CURRENCYENUM_MERGE_NONSTANDARD_VALUE
    return nil
}

// NewCurrencyEnumFromValue returns a pointer to a valid CurrencyEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCurrencyEnumFromValue(v string) (*CurrencyEnum, error) {
	ev := CurrencyEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
        ev := CURRENCYENUM_MERGE_NONSTANDARD_VALUE
        return &ev, nil
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CurrencyEnum) IsValid() bool {
	for _, existing := range allowedCurrencyEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CurrencyEnum value
func (v CurrencyEnum) Ptr() *CurrencyEnum {
	return &v
}

type NullableCurrencyEnum struct {
	value *CurrencyEnum
	isSet bool
}

func (v NullableCurrencyEnum) Get() *CurrencyEnum {
	return v.value
}

func (v *NullableCurrencyEnum) Set(val *CurrencyEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableCurrencyEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableCurrencyEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurrencyEnum(val *CurrencyEnum) *NullableCurrencyEnum {
	return &NullableCurrencyEnum{value: val, isSet: true}
}

func (v NullableCurrencyEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurrencyEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

