/*
 * Merge Accounting API
 *
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * API version: 1.0
 * Contact: hello@merge.dev
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merge_accounting_client

import (
	"encoding/json"
)

// InvoiceEndpointRequest struct for InvoiceEndpointRequest
type InvoiceEndpointRequest struct {
	Model InvoiceRequest `json:"model"`
	// raw json response by property name
	ResponseRaw map[string]json.RawMessage `json:"-"`
}

// NewInvoiceEndpointRequest instantiates a new InvoiceEndpointRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceEndpointRequest(model InvoiceRequest) *InvoiceEndpointRequest {
	this := InvoiceEndpointRequest{}
	this.Model = model
	return &this
}

// NewInvoiceEndpointRequestWithDefaults instantiates a new InvoiceEndpointRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceEndpointRequestWithDefaults() *InvoiceEndpointRequest {
	this := InvoiceEndpointRequest{}
	return &this
}

// GetModel returns the Model field value
func (o *InvoiceEndpointRequest) GetModel() InvoiceRequest {
	if o == nil {
		var ret InvoiceRequest
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *InvoiceEndpointRequest) GetModelOk() (*InvoiceRequest, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *InvoiceEndpointRequest) SetModel(v InvoiceRequest) {
	o.Model = v
}

func (o InvoiceEndpointRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["model"] = o.Model
	}
	return json.Marshal(toSerialize)
}

func (v *InvoiceEndpointRequest) UnmarshalJSON(src []byte) error {
    type InvoiceEndpointRequestUnmarshalTarget InvoiceEndpointRequest

	var intermediateResult InvoiceEndpointRequestUnmarshalTarget
	var err1 = json.Unmarshal(src, &intermediateResult)
    if err1 != nil {
        return err1
    }
    var err2 = json.Unmarshal(src, &intermediateResult.ResponseRaw)
	if err2 != nil {
		return err2
	}

	*v = InvoiceEndpointRequest(intermediateResult)
	return nil
}
type NullableInvoiceEndpointRequest struct {
	value *InvoiceEndpointRequest
	isSet bool
}

func (v NullableInvoiceEndpointRequest) Get() *InvoiceEndpointRequest {
	return v.value
}

func (v *NullableInvoiceEndpointRequest) Set(val *InvoiceEndpointRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceEndpointRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceEndpointRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceEndpointRequest(val *InvoiceEndpointRequest) *NullableInvoiceEndpointRequest {
	return &NullableInvoiceEndpointRequest{value: val, isSet: true}
}

func (v NullableInvoiceEndpointRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceEndpointRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	var err1 = json.Unmarshal(src, &v.value)
    if err1 != nil {
        return err1
    }
    return json.Unmarshal(src, &v.value.ResponseRaw)
}


